---
repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-poetry/poetry
    rev: 2.0.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-toml
      - id: check-yaml
      # - id: pretty-format-json
      #   args: [--indent=4, --autofix]
      - id: end-of-file-fixer
      # - id: double-quote-string-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations

  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
      - id: rm-unneeded-f-str

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - --quiet
        files: ^((src|examples|tests)/.+)?[^/]+\.py$
        language_version: python3

  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.12.0
  #   hooks:
  #       - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((src|examples)/.+)?[^/]+\.py$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=additionals,alle,alot,ba,bre,bund,datas,dof,dur,ether,farenheit,falsy,fo,haa,hass,hist,iam,iff,iif,incomfort,ines,ist,lightsensor,mut,nam,nd,pres,pullrequests,referer,resset,rime,ser,serie,sur,te,technik,ue,uint,unsecure,visability,wan,wanna,withing,zar
          - --skip="./.*,*.csv,*.json,*.lock"
          - --quiet-level=2
        exclude_types: [csv, json]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.7.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # pre-commit run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py310-plus
          - --force
          - --keep-updates
        files: ^(src|tests|examples)/.+\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        pass_filenames: false
        additional_dependencies: [pydantic]

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.391
    hooks:
      - id: pyright

  - repo: local
    hooks:
      - id: pytest
        name: 🧪 Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: poetry run pytest
        pass_filenames: false